print("Ian Mapacpac")
print("Zone 4 Brgy Tabi Boac, Marinduque")
print("June 17, 2002")
print("CEIIT")
print("IIST")
print("BSI/T")
print("2A")
print("Play")
print("Eat")
print("Sleep")
print("Read")
print("Watch Movies")